config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    extend FriendlyId
    friendly_id :title, use: :slugged

    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    paginates_per 10

    def tag_list
      self.tags.collect do |tag|
        tag.name
      end.join(", ")
    end

    def tag_list=(tags_string)
      tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
      new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
      self.tags = new_or_found_tags
    end

end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :tags

  def tags
    Tag.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order("created_at desc").page(params[:page])
    respond_to do |format|
      format.html
      format.atom
    end
  end

  def show
    @article = Article.friendly.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:from, :title, :body, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.friendly.find(params[:id])
    @articles = @tag.articles.order("created_at desc").page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def art_title(text)
    text.sub("[FreeBSD-Announce]","").sub("[Midnightbsd-security]","")
  end

  def art_date(text)
    text.strftime("%e %B, %Y")
  end

  def art_body(text)
    text.lines.map { |c| c.unpack("M*") }.join.force_encoding('UTF-8')
  end

  def motif_image_url(url: root_url)
    "https://motif.imgix.com/i?url=#{u url}&image_url=#{u image_url '/img/pankaj-patel-fvMeP4ml4bU-unsplash.jpg' }&color=b1d6f4&logo_url=#{u image_url '/img/bsdsec.png' }&logo_alignment=top%2Ccenter&text_alignment=bottom%2Ccenter&logo_padding=70&font_family=Avenir%20Next%20Demi%2CBold&text_color=1d1d1d"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */

    var disqus_config = function () {
        this.page.url = ENV["PAGE_URL"];  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = ENV["PAGE_IDENTIFIER"]; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//bsdsec.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/index.html.erb
<% content_for :meta do %>
  <!-- COMMON TAGS -->
  <title>BSDSec - Deadsimple BSD Security Advisories and Announcements</title>
  <!-- Search Engine -->
  <meta name="description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta name="image" content="<%= motif_image_url %>">
  <!-- Schema.org for Google -->
  <meta itemprop="name" content="BSDSec - BSD Security Advisories">
  <meta itemprop="description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta itemprop="image" content="<%= motif_image_url %>">
  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="BSDSec - BSD Security Advisories">
  <meta name="twitter:description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta name="twitter:site" content="https://bsdsec.net">
  <meta name="twitter:image" content="<%= motif_image_url %>">
  <!-- Twitter - Article -->
  <!-- Open Graph general (Facebook, Pinterest & Google+) -->
  <meta property="og:title" content="BSDSec - BSD Security Advisories">
  <meta property="og:description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta property="og:image" content="<%= motif_image_url %>">
  <meta property="og:type" content="article">
  <meta property="og:url" content="<%= root_url %>">
<% end %>

<div>
  <% @articles.each do |article| %>
    <h2>
      <span><%= art_date(article.created_at) %></span>
      <%= link_to art_title(article.title), article_path(article), class: "article_link", title:art_title(article.title) %>
      <% article.tags.each do |tag| %>
        <span> <%= link_to tag.name, tag_path(tag), title: "articles tagged with " + tag.name %></span>
      <% end %>
    </h2>
  <% end %>
  <%= paginate @articles %>
</div>

app/views/articles/show.html.erb
<% content_for :meta do %>
  <!-- COMMON TAGS -->
  <title><%= art_title(@article.title) %></title>
  <!-- Search Engine -->
  <meta name="description" content="<%= @article.body[0..200] %>...">
  <meta name="image" content="<%= motif_image_url(url: article_url(@article)) %>">
  <!-- Schema.org for Google -->
  <meta itemprop="name" content="<%= @article.title %>">
  <meta itemprop="description" content="<%= @article.body[0..200] %>...">
  <meta itemprop="image" content="<%= motif_image_url(url: article_url(@article)) %>">
  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="<%= @article.title %>">
  <meta name="twitter:description" content="<%= @article.body[0..200] %>...">
  <meta name="twitter:site" content="https://bsdsec.net">
  <meta name="twitter:image" content="<%= motif_image_url(url: article_url(@article)) %>">
  <!-- Twitter - Article -->
  <!-- Open Graph general (Facebook, Pinterest & Google+) -->
  <meta property="og:title" content="<%= @article.title %>">
  <meta property="og:description" content="<%= @article.body[0..200] %>...">
  <meta property="og:image" content="<%= motif_image_url(url: article_url(@article)) %>">
  <meta property="og:type" content="article">
  <meta property="og:url" content="<%= article_url(@article) %>">
  <!-- Open Graph - Article -->
  <meta property="article:section" content="Technology">
  <meta property="article:published_time" content="<%= @article.created_at %>">
<% end %>

<article>
  <h2 class="article_title"><%= art_title(@article.title) %></h2>
  <p class="article_info">
    <%= art_date(@article.created_at)%> by <%= @article.from %> |
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag), title: "articles tagged with " + tag.name %>
    <% end %>
  </p>
  <pre><%= art_body @article.body %></pre>
  <%= render "disqus" %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="flattr:id" content="en32oj">
  <meta property="og:image" content="<%= asset_pack_url 'media/images/bsdsec.png' %>" />
  <meta name="description" content="Deadsimple BSD Security Advisories and Announcements">
  <link href='//fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_pack_tag 'application' %>
  <%= auto_discovery_link_tag(:rss, articles_url(:format => :atom)) %>
  <%= yield(:meta) %>
</head>
<body>
<header>

<h1 class="site_title"><%= link_to "BSDSec", root_path, title:"deadsimple BSD Security Advisories and Announcements" %> </h1>
<div class="social">
  <%= link_to "/articles.atom", class: "fa-lg", title: "Subscribe"  do %>
    <i class="fas fa-rss"></i>
  <% end %>
  <%= link_to "https://github.com/hovancik/BSDSec",class: "fa-lg",title: "fork me" do %>
    <i class="fab fa-github"></i>
  <% end %>
  <%= link_to "https://twitter.com/bsdsec", class: "fa-lg",title: "Twitter" do %>
    <i class="fab fa-twitter"></i>
  <% end %>
</div>
<p class="site_subtitle">deadsimple BSD Security Advisories and Announcements </p>
</header>
<main>
<%= yield %>
</main>
<footer>
<p>
  <% tags.each_with_index do |tag, i| %>
    <%= link_to tag.name.upcase, tag_path(tag),title: "articles tagged with " + tag.name %>
    <% if i < tags.length - 1 %>
      |
    <% end %>
  <% end %>
</p>
<p>made with &hearts; by <%= link_to "Jan Hovancik", "http://hovancik.net", title:"Website of Jan Hovancik" %> </p>
 <div class="social">
  <%= link_to "/articles.atom", title: "Subscribe" do %>
    <i class="fas fa-rss"></i>
  <% end %>
  <%= link_to "https://github.com/hovancik/BSDSec" ,title: "fork me" do %>
    <i class="fab fa-github"></i>
  <% end %>
  <%= link_to "https://twitter.com/bsdsec" ,title: "Twitter" do %>
    <i class="fab fa-twitter"></i>
  <% end %>
</div>
<div class="sponsor">
  <a href="https://github.com/sponsors/hovancik">
    <img alt="Become a Sponsor!" src="https://img.shields.io/static/v1?label=Sponsor&amp;message=%E2%9D%A4&amp;logo=GitHub&amp;color=success">
  </a>
  <a href="https://www.patreon.com/hovancik" rel="nofollow">
    <img alt="Become a Patron!" src="https://img.shields.io/static/v1?label=Sponsor&amp;message=%E2%9D%A4&amp;logo=Patreon&amp;color=success">
  </a>
</div>
</footer>
</body>
</html>

app/views/tags/show.html.erb
<% content_for :meta do %>
  <title>BSDSec - Deadsimple BSD Security Advisories and Announcements</title>
  <!-- Search Engine -->
  <meta name="description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta name="image" content="<%= motif_image_url %>">
  <!-- Schema.org for Google -->
  <meta itemprop="name" content="BSDSec - <%= @tag.name %> Security Advisories">
  <meta itemprop="description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta itemprop="image" content="<%= motif_image_url %>">
  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="BSDSec - <%= @tag.name %> Security Advisories">
  <meta name="twitter:description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta name="twitter:site" content="https://bsdsec.net">
  <meta name="twitter:image" content="<%= motif_image_url %>">
  <!-- Twitter - Article -->
  <!-- Open Graph general (Facebook, Pinterest & Google+) -->
  <meta property="og:title" content="BSDSec - <%= @tag.name %> Security Advisories">
  <meta property="og:description" content="Deadsimple BSD Security Advisories and Announcements">
  <meta property="og:image" content="<%= motif_image_url %>">
  <meta property="og:type" content="article">
  <meta property="og:url" content="<%= tag_url(@tag) %>">
<% end %>

<% @articles.each do |article| %>
  <h2><span><%= art_date(article.created_at) %></span>
    <%= link_to art_title(article.title), article_path(article), title:art_title(article.title) %>
    <% article.tags.each do |tag| %>
      <span><%= link_to tag.name, tag_path(tag), title: "articles tagged with " + tag.name  %></span>
    <% end %>
  </h2>
<% end %>
<%= paginate @articles %>